### ISSUE TITLE
是否考虑增加其他图床

### ISSUE THREAD

**Issue by yongman** [hulizhen/cuImage#14]
看到七牛官网对于临时域名的限制，临时域名有效期30天，过期后自动删除，所以对于国外没有备案的域名，使用起来就比较鸡肋了，是否考虑增加`Flickr`或者`Imgur`图床支持？

**Comment by hulz413** [comment]
嗨，非常感谢你的支持，不过 cuImage 目前没有支持其他图床的计划，实在抱歉 :(

**Comment by sundl123** [comment]
希望支持其他图床，比如阿里云，腾讯云。如果支持比较全面的话，做成收费的也可以接受。

**Comment by hulz413** [comment]
> 希望支持其他图床，比如阿里云，腾讯云。如果支持比较全面的话，做成收费的也可以接受。

@SupermeReturns 嗨，cuImage 不考虑支持其他图床了，抱歉。可以考虑下 iPic，做得挺不错的哈。
