### ISSUE TITLE
当上传的图片名称中有空格时，生成的链接大部分markdown编辑器无法渲染

### ISSUE THREAD

**Issue by wjk930726** [hulizhen/cuImage#6]
希望加入%20转义

**Comment by hulizhen** [comment]
@wjk930726 嗨，我把你提交的代码改成了 Swift 风格的代码合进 develop 分支了，多谢你的贡献哈~

**Comment by wjk930726** [comment]
我主要就是改一下好自己用，顺便提交一下的。swift的字符串不怎么会用啊，所以才改成那样的_(:_」∠)_

**Comment by hulizhen** [comment]
@wjk930726 👍
