### ISSUE TITLE
图片上传成功后，能否将url中的空格编码一下

### ISSUE THREAD

**Issue by wangduanduan** [hulizhen/cuImage#9]
首先，我觉得你做的这个App，非常好用的。但是还是有一点点小瑕疵，如果能够稍微改变一下，就很完美了。

例如我用mac截图，文件名中往往都带有空格：
```
Screen Shot 2018-01-28 at 7.06.56 PM
```

往往返回的图片链接中也有空格，有些markdown解析器可能就无法成功解析图片地址。

建议将空格进行url编码后，再写入剪贴板。

或者，我们并不关心图片的文件名，你也可以给图片先重命名一个uuid后，再上传。

谢谢！

**Comment by hulizhen** [comment]
Hi，这个问题之前已经处理过了哈，可能还没合到master分支上哈https://github.com/hulizhen/cuImage/issues/6
